name: CICD
on: 
  push: 
    branches: 
    — master 
#    — staging
#    — develop 
  pull_request: 
    branches: 
    — master 
#    — staging 
#    — develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2
    - name: Setup Go
      uses: actions/setup-go@2
      with:
        go-version: '1.15.7'
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: build
      run: go build .  
    - name: Run vet&lint
      run: |
        go vet . 
        golint .  
    - name: Run tests.
      run: cd test && go test -v
    - name: Send slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   if: ${{ github.ref == ‘refs/heads/master’ && github.event_name == ‘push’ }} 
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Deploy to Docker registry
  #     uses: docker/build-push-action@v1
  #     with:
  #       username: ${{ secrets.DOCKER_USERNAME }}
  #       password: ${{ secrets.DOCKER_PASSWORD }}
  #       repository: wilsontanwm/gosimple
  #       tag_with_ref: true